### ISSUE TITLE
What is the relationship between PKIX_Test_4 and PKIX_Test_15?

### ISSUE THREAD

**Issue by MKSCertiPath** [GSA/piv-conformance#102]
They seem to contradict each other. What are the cases where Test 4 applies vs. Test 15?

**Comment by bob-fontana** [comment]
PKIX_Test_15 is for the Digital Signature Certificate and PKIX_Test_4 is for the PIV Authentication Certificate.

There are enough differences between certificates on a PIV card, that tests needed to be parameterized or additional atoms created.
