### ISSUE TITLE
PKIX_Test_20: The test does not check if extendedKeyUsage asserts any other OIDs other than id-PIV-cardAuth

### ISSUE THREAD

**Issue by MKSCertiPath** [GSA/piv-conformance#103]
The PKIX_Test_20 Confirms id-PIV-cardAuth 2.16.840.1.101.3.6.8 exists in extendedKeyUsage extension.
It does not check if any other OID was also asserted, which is also a requirement.

**Comment by bob-fontana** [comment]
This will need to be split.

**Comment by bob-fontana** [comment]
Fixed.
