### ISSUE TITLE
Failure Noted - 9.1.1.1	Validate that CBEFF structure conforms to SP800-76 Table 13

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#123]

**Comment by bob-fontana** [comment]
This how these test cases should be laid out.
**Test Case Identifier | Requirement | Atoms |**
**9.1.1 | CBEFF Structure for Fingerprint Template**
9.1.1.1 | BDB length field is non-zero | 76.1 |
9.1.1.2 | Recorded length matches actual BDB length | 76.2 |
9.1.1.3 | SB length field is non-zero | 76.1 |
9.1.1.4 | Recorded length matches actual SB length | 76.3 |
**9.1.2 | CBEFF Header for Fingerprint Template |  |**  
9.1.2.1 | Card   Holder Fingerprint object length equals sum of CBEFF header length + BDB   length + SB length | 76.5 |

I'm going to go ahead and make these changes.

**Comment by bob-fontana** [comment]
This is fixed in commit #00146c8
