### ISSUE TITLE
Failure Noted - 9.1.2.8	Validate that for the mandatory minutia PIV card templates, the CBEFF biometric data type encoding value shall be b100xxxxx, which corresponds to biometric data that has been processed.

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#125]

**Comment by MKSCertiPath** [comment]
Verified that CBEFF biometric data type encoding for mandatory minutia PIV Card templates is indeed b100xxxxx as shown below: 0x80 === b100xxxxx

![image](https://user-images.githubusercontent.com/9324182/60182648-af462380-97f2-11e9-890a-915b66487278.png)
