### ISSUE TITLE
Fail - 9.2.1.1	Validate that CBEFF structure conforms to SP800-76 Table 7

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#126]

**Comment by MKSCertiPath** [comment]
Verified that 9.2.1.1 conforms to the CBEFF structure as per SP800-76 Table 7

![image](https://user-images.githubusercontent.com/9324182/60181736-dd2a6880-97f0-11e9-96b6-e7e82674f307.png)
