### ISSUE TITLE
Fail 9.2.2.8	Validate that the CBEFF biometric data type encoding value shall be b001xxxxx, which corresponds to the raw biometric data

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#128]

**Comment by MKSCertiPath** [comment]
The value in the CBEFF biometric data type encoding is 0x20 which matches the requirement of b001xxxxx

![image](https://user-images.githubusercontent.com/9324182/60058034-cc74d800-96b4-11e9-80ae-692c621ceb82.png)
