### ISSUE TITLE
Middleware API should emulate middleware API SP 800-73-4 Section 3

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#19]
The PIV middleware API will use the same return, input, and output structure as the middleware API described in SP 800-73-4, Section3 *Client Application Programming Interface*.  Supported methods/functions are:
- [x] `pivMiddlewareVersion`
- [x] `pivConnect`
- [x] `pivDisconnect`
- [x] `pivSelectCardApplication` 
- [x] `pivLogIntoCardApplication`
- [x] `pivGetData`
- [x] `pivCrypt`
- [x] `pivPutData`
- [x] `pivGenerateKeyPair`

The exception(s) to this story will be:
- `pivEstablishSecureMessaging`

The `versionString` output value from `pivMiddlewareVersion` will contain "`800-73-4 Client API`".

**Comment by geoffbeier** [comment]
Added progress tracking, associated with cards in project tracker

**Comment by bob-fontana** [comment]
This is working but not fully exercised.
