### ISSUE TITLE
CCT GUI - selecting new database needs to clear tree decorators

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#191]
If you don't restart the GUI, the previous selected database appears to be running - regardless of selecting the new db.

**Comment by bob-fontana** [comment]
I believe it's not the database restart that's not effective, I think it's the cached container objects in the singleton aren't getting set back to null.

**Comment by bob-fontana** [comment]
The container cache needs to be cleared when the _Verify PIN and Execute Tests_ button is clicked.  That should cover all cases (different card, different PIN, different database, change in overrides).

**Comment by agalustyan** [comment]
Created a new method in https://github.com/GSA/piv-conformance/commit/524a6e25820ca66f6acdb8b9816c1415af78854b to clear up cached containers.  Initially wasn't able to call it but then figured out a way but this didn't have the desired effect there must still be things that need to be cleaned up.

**Comment by bob-fontana** [comment]
Agreed.  The decorators in the tree should be changed back to "untested."

**Comment by bob-fontana** [comment]
Fixed.

**Comment by bob-fontana** [comment]
Confirmed.
