### ISSUE TITLE
GUI - Add two buttons "PIV" and "PIV-I" that will by default open the appropriate, accompanying database. 

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#192]
Either add them to the menu bar with the 4 other buttons, or to the main page of the GUI, somewhere that makes sense - under the GSA logo?

**Comment by agalustyan** [comment]
Added the plumbing and 2 buttons in https://github.com/GSA/piv-conformance/commit/524a6e25820ca66f6acdb8b9816c1415af78854b.  The icons for the buttons will likely need to be changed.

**Comment by agalustyan** [comment]
Added 2 buttons and all the needed bumbling in https://github.com/GSA/piv-conformance/commit/524a6e25820ca66f6acdb8b9816c1415af78854b.  Icons for the buttons will likely need to change.

**Comment by bob-fontana** [comment]
Fixed
