### ISSUE TITLE
11.1.2.4 - PIV interim extension is present

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#203]

**Comment by bob-fontana** [comment]
This test case is probably unnecessary.  It's just to check that the extension is present and contains a boolean value for PIV cards only.  Whether a PIV-I card does/does not assert the interim flag should have no effect on the relying party unless the relying party doesn't distinguish between PIV and PIV-I.  That's out of scope for PIV-I.

**Comment by bob-fontana** [comment]
Remove the test case from the database.  Lowering the severity.
