### ISSUE TITLE
Remove Test Cases -  BDB FASC-N/CHUID FASCN N/A for PIV-I

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#209]
Update spreadsheet and new db file

**Comment by agalustyan** [comment]
Updated spreadsheet and databases in https://github.com/GSA/piv-conformance/commit/524a6e25820ca66f6acdb8b9816c1415af78854b

**Comment by agalustyan** [comment]
Updated the spreadsheets and the databases in https://github.com/GSA/piv-conformance/commit/524a6e25820ca66f6acdb8b9816c1415af78854b

**Comment by bob-fontana** [comment]
Confirmed.
