### ISSUE TITLE
Current Policy on a user creating their own backup of their PIV/HSPD-12 cert?

### ISSUE THREAD

**Issue by JJediny** [GSA/piv-conformance#215]
As a Government PIV user, I want to know the legal standing of my ability to back up my own HSPD-12 issued cert onto a FIPS-compliant device (e.g. https://www.yubico.com/business/product/yubikey-fips) in the event of physical damage to either my HSPD-12's smart card chip or my government-issued card reader, that I'd be able to use my backup device in lieu?

**Comment by bob-fontana** [comment]
You can use any number of open source tools to extract the containers from your card.  However, your private keys and PIN are not exportable.  So, if you lost your PIV, your Yubikey will not work properly for some use case scenarios, particularly if your applications leverage the smart card private keys to sign and encrypt things.

**Comment by bob-fontana** [comment]
Closing this issue.  This should be addressed in another forum.  These issues are about building the tool.
