### ISSUE TITLE
Add License and Contributing

### ISSUE THREAD

**Issue by lachellel** [GSA/piv-conformance#218]
For govt compliance purposes, a License.md and Contributing.md needs to be added. 

- A sample License.md: https://github.com/GSA/piv-guides/blob/staging/LICENSE.md
- A sample Contributing.md: https://github.com/GSA/piv-guides/blob/staging/CONTRIBUTING.md
  - The Contributing.md needs the Licensing disclaimer primarily

**Comment by bob-fontana** [comment]
Thanks LRL.

**Comment by bob-fontana** [comment]
Fixed
