### ISSUE TITLE
Test case numbers and descriptions on SP 800-85B Reference tab don't match Step Overview tab

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#233]
These 4 test cases, all mention tables in 800-73-4, and two mention 'container size' and two mention 'certificate length'.  We should verify these are testing  in a similar fashion, and update the language accordingly.

The second portion of this fix, after reviewing the code performing the tests, these values are ***Recommended by NIST rather than a hard value.  Should we adjust our reporting to say that, and maybe give a yellow, warning flag rather than red failure flag.

**Comment by bob-fontana** [comment]
The purpose of the length-check branch was to implement actual length checking.  So the tool now implements length checking using the same consistent mechanics and is based on the elements in each container.  I think that verifies the first part of this bug and might suggest that we make sure we properly state what it does.

In SP 800-85B-4_draft.pdf, the requirements for the individual tags comes from this language in TE04.01.01.01: 

The tester shall validate that the formatting, encoding and the content of all the elements in each data container conforms to SP80073 Part 1.  The next level down from a container is "tags". Each container in the data model has a prescribed set of tags that are most often associated only with a particular container type.  So, certificates (there are multiple types), share the same set of tags, with the real "data" being in Tag 70.  

You will see now in the database (.xlsx files), that follows this test case description pattern.  I did *not* go back to the first tag of each of the worksheet and duplicate the requirement statement in Column B.  That's a clerical task.  I've made sure that all of the logs contain the real requirements.

"CCC value lengths comply with Table 8 of SP 800-73-4"

Having said that, the "*" items in various containers is clearly an open item.  
--

**Comment by bob-fontana** [comment]
Because Column C on the second "Steps Overview" is the real test case description, we should remove the first tab from the workbooks and modify the python script accordingly.  That little investment will solve the first half of this issue and reduce the amount of labor needed to update these sheets properly.

**Comment by bob-fontana** [comment]
Updates made, needs QA.

**Comment by bob-fontana** [comment]
This is all completed.
