### ISSUE TITLE
Description for test 11.1.2.5 should probably be changed to "Private key corresponds to the public key contained in the certificate as the signature verification succeeds."

### ISSUE THREAD

**Issue by dbcolston** [GSA/piv-conformance#255]
The description for this test should probably be changed to "Private key corresponds to the public key contained in the certificate as the signature verification succeeds." to make it be consistent with the wording for the private key/public key testing for the Digital Signature Certificate, the Key Management Certificate, and the Card Authentication Certificate.

**Comment by bob-fontana** [comment]
Fixed in commit #1269545
