### ISSUE TITLE
Handle extra 0xFE tag in CHUID and Printed Information

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#26]
In the CHUID object of the test cards, there is a zero-length 0xFE tag just before the signature.  In the Printed Information object, there is a zero-length extra 0xFE tag at the end of the object.  These should be ignored anyway, but this task is just to ensure that the extra 0xFE tags identified here are ignored.  The test card object repo has been updated with correctly formed objects.

**Comment by geoffbeier** [comment]
This is addressed in the processing and in new cards.
