### ISSUE TITLE
Not seeing the "Override test OIDs" option

### ISSUE THREAD

**Issue by DanHelveston** [GSA/piv-conformance#269]
I'm following the Card Conformance Tool (CCT) documentation in the wiki.  I am testing a PIV-I card that uses VeriSign/Symantec/DigiCert MPKI OIDs (2.16.840.1.113733...) and cannot locate the "Edit > Override test OIDs" option.  At the FIPS 201 Card Conformance Tool v0.1.8-Beta.jar menu, the Edit option only has Cut, Copy, Paste options.  I ran the tests.  Five of them failed due to the Policy OID difference.  I'm using the PIV-I_Production_Cards.db.

Also, the 10.5.1.4 test failed. I find enough detail in the logs to understand what the issue is.

**Comment by DanHelveston** [comment]
I figured out the 10.5.1.4 - it is the Iris detail. I discovered that the debug log has summary info at the top of the file and the detail later in the log file. The detailed log section helped me figure it out.  My PIV-I customer does not collect Iris data, nor populate that container on the card - hence the failure.  It is a false negative.   Still cannot find the Override test OIDs option...

**Comment by bob-fontana** [comment]
The override button is getting deprecated. Mapped certificate policy OIDs will be tested in PKIX.6 and it will not be necessary to make any configuration changes to automatically pick up the correct trust anchors and intermediate CA certs.

**Comment by DanHelveston** [comment]
Hi Bob!  Thanks for the clarification.  I will go with what I have.
