### ISSUE TITLE
Build/Packaging System Setup

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#3]
Packaging for end-use is primary focus, packaging for developers is secondary.  Deliverable is a method for installing and running (or demo'ing) the tool starting with the second sprint.

**Comment by geoffbeier** [comment]
The purpose of this task is to get the tools set up that will manage building and packaging for the PIV conformance tester.

Some combination of ant, gradle and maven will be used to drive the production of a runnable binary from the git repository.

As we perform this task we will:

1. Define how we'll use these tools.
2. Write preliminary build files to drive generation of test binaries.
3. Configure them so our dependencies can be added to the build process readily.

**Comment by bob-fontana** [comment]
Will we start with a Hello, World application or do you want to stand up a skeletal OSGI application like [https://github.com/teverett/osgi-example](https://github.com/teverett/osgi-example)?

**Comment by geoffbeier** [comment]
A snapshot of current thinking with regard to gradle + maven usage for commons, junit, slf4j, log4j and Bouncy Castle has been attached to issue 6. Once the wuff update is complete and published, that will be expanded and moved into the repository to close this issue out.
