### ISSUE TITLE
Key Management Certificate and Card Authentication Certificates are not checking that the expiration date does not go beyond the Card Expiration Date

### ISSUE THREAD

**Issue by dbcolston** [GSA/piv-conformance#304]

**Comment by ryancdickson** [comment]
@dbcolston - reviewing [800-85B-4](https://csrc.nist.gov/csrc/media/publications/sp/800-85b/4/draft/documents/sp800_85b-4_draft.pdf) it seems as if expiration comparison test cases only exist for the PIV Authentication and Digital Signature certificates.

<br>

```AS07.01.15: The expiration of the PIV authentication certificate is not beyond the expiration of the CHUID.```

```AS07.02.11: The expiration of the digital signature certificate is not beyond the expiration of the CHUID.```

<br>AS04.03.01 indicates the CHUID expiration date shall be the same as printed on the card - limiting the expiration of the certificates above to the card's expiration.

We'll check with colleagues at NIST to learn if future revisions of 800-85B will extend the validity checks to other types of certificates found on PIV cards - and have tagged this issue with the "enhancement" label for consideration in future updates of the tool.  I can't think of a scenario where we'd want any of the certificates' validity to extend beyond the card's expiration.

Thanks for your feedback!
