### ISSUE TITLE
test 11.2.2.5 doesn't recognize Policy Identifier=2.16.840.1.101.3.2.1.3.7 being present in the certificate

### ISSUE THREAD

**Issue by dbcolston** [GSA/piv-conformance#308]
The Digital Signature Certificate being tested contains a policy identifier of 2.16.840.1.101.3.2.1.3.7, however the test tool is failing this test case.

            X509v3 Key Usage: critical
                Digital Signature, Non Repudiation
            X509v3 Certificate Policies: 
                Policy: 2.16.840.1.101.3.2.1.3.7

**Comment by grandamp** [comment]
Technically, they can also be mapped policies too. This would apply for both signature and encryption certificates.
