### ISSUE TITLE
test 11.3.2.4 doesn't support Policy Identifier=2.16.840.1.101.3.2.1.3.6 being present in the certificate

### ISSUE THREAD

**Issue by dbcolston** [GSA/piv-conformance#309]
The Key Management Certificate being tested contains a policy identifier of 2.16.840.1.101.3.2.1.3.6, however the test tool is failing this test case.  According to "Common Policy X.509 Certificate and Certificate Revocation List (CRL) Profiles", Version 2.1, February 1, 2021:

	One or more of the following policies must be asserted: 
		2.16.840.1.101.3.2.1.3.6 id-fpki-common-policy
		2.16.840.1.101.3.2.1.3.7 id-fpki-common-hardware
		2.16.840.1.101.3.2.1.3.16 id-fpki-common-High

**Comment by grandamp** [comment]
Technically, they can also be mapped policies too. This would apply for both signature and encryption certificates.
