### ISSUE TITLE
test 11.7.2.4.1 doesn't support Policy Identifier=2.16.840.1.101.3.2.1.3.39 being present in the certificate

### ISSUE THREAD

**Issue by dbcolston** [GSA/piv-conformance#311]
The Content Signing Certificate being tested contains a policy identifier of 2.16.840.1.101.3.2.1.3.39, however the test tool is failing this test case.  

            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Certificate Policies: 
                Policy: 2.16.840.1.101.3.2.1.3.39

**Comment by grandamp** [comment]
Technically, they can also be mapped policies too.  This would apply for both signature and encryption certificates.

**Comment by dbcolston** [comment]
Yes, but in our case, they are present in the certificate itself so I don’t think that mapping is needed.

 

Barry

**Comment by bob-fontana** [comment]
If memory serves correctly, the way this should work is that the  PDVAL stuff should be handled by Sun or BC depending on which you've configured the software to use. They are not designed to work together, (Sun + BC).  Pick one that works. Policy mapping was supported using either, however, my own mileage varied and took quite a bit of fussing with the PDVAL code to get support for both.

Ensure the up-to-date trust anchors are specified in the config files.

The spreadsheet has a crude way to specify for certificate policies are expected to be in a certificate. We built out a few examples, however, there is still a manual step of creating the databases from the spreadsheet sources. I'm no sure how much of that process was documented. Look in the venv subdirectory for some clues.

Direct policies may not work concurrently. In other words, if there is policy mapping going on for some certs but no policy mapping for others, it's possible that one or the other doesn't work. I didn't look into that very far.
