### ISSUE TITLE
Hyperlink on [https://github.com/GSA/piv-conformance/wiki/Running-the-CCT] 

### ISSUE THREAD

**Issue by cffraser1** [GSA/piv-conformance#312]
The hyperlink at https://github.com/GSA/piv-conformance/wiki/Running-the-CCT under 1. Running the card conformance tool, which should leads to the page to download the tool, leads to a gihhub.com URL which is deceiving and possibly malicious.

**Comment by claytonjbarnette** [comment]
Updated link to point to CCT releases.
