### ISSUE TITLE
Test sp800_76Test_28 (checking Extended data block length is 0) uses one byte from the Fingerprint Minutiae

### ISSUE THREAD

**Issue by baud001** [GSA/piv-conformance#314]
In the sp800_76Test_28, the code copying the Extended Data Block Length [data](https://github.com/GSA/piv-conformance/blob/master/conformancelib/src/main/java/gov/gsa/pivconformance/conformancelib/tests/SP800_76_Tests.java#L1174) is off by one, copying the last byte of the fingerprint minutiae and the first byte of the Extended Data Block Length, instead of the two bytes of the Extended data block length.

Of course the last byte of the fingerprint minutiae can be 0, thus the test succeeding, even when testing wrong data.

It seems that the fix could just be changing the parameters in the Arrays.copyOfRange method:
from
`Arrays.copyOfRange(biometricDataBlock, offset+numberOfMinutiae*6+3, offset+numberOfMinutiae*6+3+2);`
to
`Arrays.copyOfRange(biometricDataBlock, offset+numberOfMinutiae*6+4, offset+numberOfMinutiae*6+4+2);`

**Comment by claytonjbarnette** [comment]
Updated the code in the `SP800_76_Tests.java` with the code below submitted by `@baud001` in this issue: 

```shell 
byte [] extendedDataBlockLength  = Arrays.copyOfRange(biometricDataBlock, offset+numberOfMinutiae*6+4, offset+numberOfMinutiae*6+4+2);
```
After client testing this error is resolved. 👍
