### ISSUE TITLE
Look at broken eclipse build

### ISSUE THREAD

**Issue by geoffbeier** [GSA/piv-conformance#32]
Eclipse currently fails to build projects that have multiple module-info.java files (e.g. between tool/library/test projects) when using its gradle plug-in.

**Comment by geoffbeier** [comment]
Behavior here was changed by but not addressed by gradle updates. Blocking finalization of merge for #19

**Comment by bob-fontana** [comment]
Seems to be working with JDK 1.8_0_201.
