### ISSUE TITLE
Create a temporary tool to create test settings databases before the GUI is in place

### ISSUE THREAD

**Issue by geoffbeier** [GSA/piv-conformance#33]
This is independent of #8 because this is not something we will expect anyone to *use* once end products are available. It is to facilitate development of the file format that will drive both GUI and #8.

- [X] Create new database
- [X] Populate from schema pulled from res tree
- [x] Populate with sample data
- [x] Save to specified location

**Comment by geoffbeier** [comment]
- [X] Create new database
- [X] Populate from schema pulled from res tree
- [ ] Populate with sample data
- [ ] Save to specified location

**Comment by bob-fontana** [comment]
This is working.  An enhancement would be to do it from JDBC.
