### ISSUE TITLE
GUI Requirements

### ISSUE THREAD

**Issue by djpackham** [GSA/piv-conformance#35]
The main users for the tool will be agency representatives who may or may not be technically savvy. We need to make the tool user friendly and easy to run.

Requirements:
- [ ] Verify the PIN first before running any test cases that require PIN. We want to avoid locking the user's PIN if it is entered incorrectly after 1 attempt.
- [ ] Test cases must be configurable (i.e. be able to enable / disable each test case). We want to be able to run all the tests cases at once, but for the test cases that fail, we want the user to be able to run just those failed test cases
- [ ] Overall, need the tool to be easily configurable and user friendly.
- [ ] Need to generate some sort of comprehensive report that can be digitally signed. Maybe look to the [x.509 cert tool](https://cpct.app.cloud.gov/) for an example. Would be nice to have similar look and feel.

**Comment by bob-fontana** [comment]
This is complete.
