### ISSUE TITLE
Need to track card type

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#39]
The card type (PIV, PIV-I, and CAC to some degree) have enough differences that some of the required data for certain objects are slightly different.  At some early point during a card validation, we need to determine the card type so that we invoke the correct logic for that card.

For instance, a PIV-I certificate *will never* have a FASC-N in the Subject Alternative Name, but you will find a FASC-N in the same card's CBEFFs.

A PIV-I CBEFF must contain the Card UUID in the signed attributes, but no FASC-N.  The signed attributes of the CBEFF from a PIV card must have both FASC-N and Card UUID in the signed CBEFF, and must have both FASC-N and Card UUID in the Subject Alternative Name in the X.509 certs on the card

A PIV content signing cert's EKU keyPurposeId is 2.16.840.1.101.3.6.7 - Always.  A  PIV-I content signing cert's EKU keyPurposeId is 2.16.840.1.101.3.8.7 - Always.

Certificate policy OIDs on PIV cards map to NIST-registered OIDs for PIV card certificates.   Certificate policy OIDs on PIV-I cards also map to NIST-registered OIDs for PIV-I card certificates, however, two bridges are involved, which will make policy mapping more complicated than this program should need to be.  We should leave mapping out-of-scope for now, but attempt to add a means to support both PIV and PIV-I KPID and certificate issuance policies.

**Comment by bob-fontana** [comment]
@geoffbeier, is there now a card type in the singleton so that within an atom, it would always know the card type (one of the 4 profiles)?  Does this even matter with parameters flowing the way they are?  I think we can remove this requirement and close this.

**Comment by grandamp** [comment]
-Certificate policy OIDs on PIV cards map to NIST-registered OIDs for PIV card certificates.

With the exception of the common-authentication (2.16.840.1.101.3.2.1.3.13), which must be directly asserted and not mapped?

**Comment by bob-fontana** [comment]
Hi Todd,

For PIV-I issuers, the normative reference I've been using is the (May 2018 profile)
[https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-x509-cert-profiles-pivi.pdf].  Is there another normative reference that covers PIV-I card auth cert policies?

**Comment by bob-fontana** [comment]
FBCA 2.31 6.2.1: PIV-I Cards are PKI tokens that have private keys associated with certificates asserting policies mapped to PIV-I hardware or PIV-I-cardAuth. Unless this has been updated, this looks like it answers the question in the previous post.

**Comment by bob-fontana** [comment]
Todd, I think I know what you';re getting at!  None of the PIV-I certificate policy OIDs are ever directly asserted.  The 4 standard profile's we're creating (one being production PIV-I), all hold the issuer domain policy OID just as a placeholder.

The CCT has a dropdown with text boxes that allow the EE certs' subject domain (unmapped) policy OIDs to override those default (mapped) values.  If you build the code right now, it's temporarily stubbed out.

**Comment by bob-fontana** [comment]
This is resolved.
