### ISSUE TITLE
Library Research

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#6]
Determine which internal and external (3rd-party) libraries will be used.  Determine 3rd-party source code licensing can meet CC1 or CC2. Test certain libraries for compatibility, robustness, accuracy, appropriateness for use, etc.  Deliverable is a document with 3rd-party licenses that will be used in the product.  This list could change in later sprints.

**Comment by geoffbeier** [comment]
In pursuing JDK 9 compatibility, it appears we need to go with RCP and SWT from the Eclipse "Oxygen" release.

**Comment by geoffbeier** [comment]
JDK 9 compatibility has been confirmed for bouncy castle. Attached is a sample project that uses most of the libraries in question. I'm mainly attaching it here for safekeeping until the longer term config is in the repository.
[bc-test.zip](https://github.com/GSA/piv-conformance/files/1656979/bc-test.zip)
