### ISSUE TITLE
Need 76.x atom to test finger quality

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#62]
SP 800-76-2: Finger Quality value shall be 20, 40, 60, 80, 100, 254, or 255.

**Comment by bob-fontana** [comment]
Atom has been added to Armen_PlaceholderTests.java its name Issue_62

**Comment by geoffbeier** [comment]
Merged into SP800_76_Tests class as "SP800-76.47"

sp800_76Test_47()

Changeset 140910b86a3f24beaf9de8e0ec187a13c71c50da

**Comment by bob-fontana** [comment]
This was tested and does not work.

**Comment by bob-fontana** [comment]
Confirmed to be working.
