### ISSUE TITLE
Need PKIX atom for checking CRL DP and AIA URI for ".crl" or ".p7c"

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#63]
11.1.2.9.2, 11.3.2.6.2, 11.3.2.5.2, 11.4.2.9.2: URI points only to files with .crl extensions.

**Comment by bob-fontana** [comment]
- [ ] Implemented as a single atom that takes a file extension as a parameter from the profile

**Comment by bob-fontana** [comment]
Implemented as a single atom that takes a file extension as a parameter from the profile Atom has been added to Armen_PlaceholderTests.java its name Issue_63_3.  Will test and close as appropriate.

**Comment by geoffbeier** [comment]
Merged into branch swig-gui-devel as member functions PKIX_Test_22, PKIX_Test_23, PKIX_Test_24, PKIX_Test_25. Not tested yet.

**Comment by bob-fontana** [comment]
Confirmed.
