### ISSUE TITLE
Need atom to check expiration date of content signing cert

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#65]
11.7.2.2: X.509 Certificate for Content Signing is not expired.

**Comment by bob-fontana** [comment]
Atom has been added to to Armen_PlaceholderTests.java its name Issue_65

**Comment by geoffbeier** [comment]
Merged into PKIX atom set with e123a218982d7a8276a2ed0a9eeef21bb12fdba4

PKIX_Test_26()

**Comment by bob-fontana** [comment]
Confirmed.
