### ISSUE TITLE
BERTLV.4 is disabled

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#68]
BERTLV.4 (berTLV_Test_4) is @Disabled, so it appears that this needs to be looked at.

**Comment by geoffbeier** [comment]
Provisionally re-enabled for testing... were this case ever violated, our TLV parser should error out, either causing an exception or a null value at the end of this test, which our assertion would catch.

**Comment by bob-fontana** [comment]
Confirmed.
