### ISSUE TITLE
Notional Skeletal GUI

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#7]
A running GUI that demonstrates the look and feel of the test framework.

**Comment by geoffbeier** [comment]
This task will result in the basic skeleton of a GUI using the Eclipse Rich Client platform. It will allow us to experiment with various graphical layouts and provide a workspace where we can test out library functionality interactively.

Once this is in place, at the end of any sprint, it should be possible to pull the project from github and run a build that results in an executable which, when launched, will display a window with some test functionality.
