### ISSUE TITLE
Set state of GUI controls appropriately if no database is opened

### ISSUE THREAD

**Issue by geoffbeier** [GSA/piv-conformance#70]
Currently, the run tests action is still enabled even if there's no database. This also causes issues with PIN entry.

(Relatively low priority because default use case will always have a DB open.)

**Comment by bob-fontana** [comment]
A properties file to save off the last database location and any other states would be helpful.

Then, don't open the database by default, but populate the *Test Database* textbox with the path and filename.  When the file selection box is displayed, that location in the filesystem is preselected although the operator can navigate anywhere else.

**Comment by bob-fontana** [comment]
Fixed
