### ISSUE TITLE
Confirm size for printed information blob test

### ISSUE THREAD

**Issue by geoffbeier** [GSA/piv-conformance#72]
The original sheet had it at 120 bytes likely based on an old version of the spec. Find the correct value and update the test case/atom

**Comment by bob-fontana** [comment]
SP 800-73-4's container sizes are the sum total of the Ls in the container's TLVs.  So, this number would be 229.  *It looks like this is how every container's size should be checked, which is probably going to be new set of issues.*

**Comment by geoffbeier** [comment]
The test was originally pulled from the BER-TLV tests for printed information object. The 120 value was in the older version of the doc. In the current draft, they've removed the size check and changed the test to read

![image](https://user-images.githubusercontent.com/133355/56459259-0c3edc80-635f-11e9-8752-4f092f0c6c33.png)

By that read, we might want to nix the length check. 

Looking at this table from 800-73

![image](https://user-images.githubusercontent.com/133355/56459286-6cce1980-635f-11e9-9b13-30e3d4eb0c86.png)

I see where 229 comes from (and that was my first instinct) but I haven't confirmed that includes Tag and Length bytes; adding those is where I came up with the temporary 245 I commited for now.

**Comment by bob-fontana** [comment]
The guidance is in an asterisked footnote at the bottom of page 27 of SP 800-73-4.

The values in the “Max. Bytes” columns denote the lengths of the value (V) fields of BER-TLV elements.

**Comment by bob-fontana** [comment]
Should we have a common utility method that sums the lengths of the value fields up for a container, such that each 74-3 atom can assert that the value returned is <= an APDUUtils.java length constant established for each container OID?
