### ISSUE TITLE
Various anomalies at card communications level

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#74]

**Comment by bob-fontana** [comment]
This looks to be not necessarily cardstock-related.  Some v7 cards read perfectly (as can be expected with 8 known defects).  Others fail at the APDU response level.  Gemalto 2.3 behaves similarly.

All ICAM test cards with the CertiPath BAP work as expected.   Those are all v8..0 2.3.5,/ 1 2.4.0

**Comment by bob-fontana** [comment]
There are multiple differences in how the same card responds to the same APDU via two different smart card drivers.  With OpenSC, there are no card communications errirs.  With PC/SC and PC/SC emulation on the Mac, we observe unexpected responses at the APDU/TDPU level in BER-TLV.  So far, it appears that no IDEMIA v8 cards are involved.

**Comment by bob-fontana** [comment]
Narrowed down to failure to receive a response for a the APDU to fetch the facial image.

**Comment by bob-fontana** [comment]
Workaround for javax.smartcardio library committed [here](https://github.com/GSA/piv-conformance/commits/card-comms-fix) but use at own risk until fully exercised.

**Comment by bob-fontana** [comment]
Confirmed fixed.
