### ISSUE TITLE
Change Application PIN prompt to PIV Application PIN

### ISSUE THREAD

**Issue by bob-fontana** [GSA/piv-conformance#75]
Need change Application PIN label to PIV Application PIN on the GUI.

**Comment by stvnewbold** [comment]
This is the text in the GUI, should we say "Card PIN" to allow for PIV/I?

**Comment by agalustyan** [comment]
Fixed in https://github.com/GSA/piv-conformance/commit/524a6e25820ca66f6acdb8b9816c1415af78854b
