### ISSUE TITLE
Add APL logo along side the GSA logo on application window

### ISSUE THREAD

**Issue by stvnewbold** [GSA/piv-conformance#77]

**Comment by bob-fontana** [comment]
Change layout to include the attached official logo.  

FIPS 201 EP logo -- let's also make it the icon at least in Windows.
![FIPS_201_Approved](https://user-images.githubusercontent.com/19328070/56574862-48a64e80-6592-11e9-89d2-e878c8366f5b.png)

**Comment by bob-fontana** [comment]
I think Matt is going to want "Approved" replaced words "Evaluation Program."

Mocked up possible replacement.  Need actual collateral for this
![FIPS_201_Evaluation_Program](https://user-images.githubusercontent.com/19328070/56655371-8ec9e380-6660-11e9-8585-c0292cb58dd4.png)
.

**Comment by stvnewbold** [comment]
Closed per Matt Arnold
