### ISSUE TITLE
sp800_73_4_Test_1 does not match test description in the 85b_test_definitions_PIV_ICAM_Test_Cards.xlsx file

### ISSUE THREAD

**Issue by MKSCertiPath** [GSA/piv-conformance#83]
The excel file says sp800_73_4_Test_1 should test "CCC   blob no larger than 297 bytes" whereas the test code (and its comment agrees) is testing "registered data model element is present and has a value of 0x10"

Either we need to update the excel to reflect what is coded or we need to write one more test atom to cover what the excel expects.
--

**Comment by bob-fontana** [comment]
The correction will be to update D2 on the SP800-73-4 tabs in the .xlsx files with:

The registered data model element is present and has a value of 0x10

**Comment by bob-fontana** [comment]
This is another incorrectly worded test case.  This was handled as of v0.0.4, commit a4fa4e9ad5d44cabde3bd681de7f12339aab291b.
