### ISSUE TITLE
Description for 800_73_4_Test_4 and code comment specify incorrect value for SECURITY_OBJECT_BUFFER_TAG

### ISSUE THREAD

**Issue by MKSCertiPath** [GSA/piv-conformance#84]
The value used in the excel and the test code comment is 0xE4 whereas the Table 8 of the NIST 800-74-4 specifies it to be 0xB4. The TagConstants file correctly defines it as 0xB4.
So we just need to update the excel and the comment in the sp800_73_4_Test_4 test atom.

**Comment by bob-fontana** [comment]
- [ ] Update the spreadsheet
- [ ] Update the atom (will handle later after inventory)
