### ISSUE TITLE
Test atom sp800_73_4_Test_6: Values of tags present conform to vendor-supplied data

### ISSUE THREAD

**Issue by MKSCertiPath** [GSA/piv-conformance#88]
Right now the test doesn't do anything. We need to create a special test where we would know the data supplied by the vendor and the test will ensure that the card has the correct tags as per the vendor supplied data. Most likely we will need to create a special card for this testing.

**Comment by bob-fontana** [comment]
There is not enough vendor information to apply this test to all vendor cards.  This test *does* perform the length check, so it shouldn't be removed.
