### ISSUE TITLE
CSV Output - Naming Considerations

### ISSUE THREAD

**Issue by ryancdickson** [GSA/piv-conformance#91]
Consider using a date+timestamp delimiter to label output files, rather than the current "number increment" model.  The existing model also re-labels outputs from previous executions, which can be confusing.

**Sample:**
- Assume I ran the tool and generated "conformance_results.1.csv"
- Upon running the tool again, "conformance_results.1.csv" is re-labeled to "conformance_results.2.csv". (The most recent execution is then labeled "conformance_results.1.csv")

**Proposed Alternative:**
- I run the tool at 3:28 pm and generate "conformance_results_043020191528.csv"
- I run the tool again at 3:33 pm and generate "conformance_results_043020191533.csv"

**Comment by bob-fontana** [comment]
Something like that is pretty easily done by editing the log4j and slf4j config files.  It's not an actual bug but rather possible annoyance to some.  If there's time left, we'll take a crack at it.

**Comment by bob-fontana** [comment]
This was corrected with ec66528c6a2f69457c691b326e647771a0ccb389.
