### ISSUE TITLE
CSV Output - conformance_results.csv Locked for Editing

### ISSUE THREAD

**Issue by ryancdickson** [GSA/piv-conformance#92]
It appears (for me) that so long as the tool is open, conformance_results.csv is locked for editing by 'another user'.

Once the tool is closed, the file is released and can be viewed without issue.

**Comment by stvnewbold** [comment]
Bob - do we want this behavior?

**Comment by bob-fontana** [comment]
Nope.  While we're at it, let's close all files, reset the tree decorators, etc. when 1) a card is changed, 2) a different database is selected, 3) if the the existing test database is (re-run for any reason).

**Comment by bob-fontana** [comment]
This was corrected with commit ec66528c6a2f69457c691b326e647771a0ccb389.

**Comment by bob-fontana** [comment]
Causes side effects.  Created csv-file-fixes branch.

**Comment by bob-fontana** [comment]
How we solve this doesn't matter  We need to be able to access the output file predictably and intuitively. The ability to display the HTML file while a test is running must be disabled.
Part I File unlock
- [ ] Ensure that the file produced from the previous run is unlocked
- [ ] Ensure that the path of the fil produced from the previous run is accessible by the display routine
- [ ] Handle multiple rollover strategies
Part II HTML display cleanup
- [ ] Disable the HTML button while test is running
- [ ] Ensure that the CSV file is viewable (has header) before displaying
- [ ] Ensure that the HTML file is viewable (has header)
Part III Rollover strategy
- [ ] Change to timestamp and database name (override user-config?)

The latest CSV file should be displayed

**Comment by bob-fontana** [comment]
I'm closing this.  After reverting all changes to look at the original bug, it's not a bug.  Reverted changes are in commit #30706ae2ebef5a5552cbf7ced2be4ca8e67bb4e4.   I would recommend that when we are in the neighborhood again we should add custom timestamp file pattern appender.
