### ISSUE TITLE
sp800_73_4_Test_38: Discovery Object blob no larger than 19 bytes; but the code checks for length <= 20 bytes

### ISSUE THREAD

**Issue by MKSCertiPath** [GSA/piv-conformance#94]
sp800_73_4_Test_38: Discovery Object blob no larger than 19 bytes; but the code checks for length <= 20 bytes

	//Discovery Object blob no larger than 19 bytes
	@DisplayName("SP800-73-4.38 test")
	@ParameterizedTest(name = "{index} => oid = {0}")
	@MethodSource("sp800_73_4_DiscoveryObjectTestProvider")
	void sp800_73_4_Test_38(String oid, TestReporter reporter) {
		
		PIVDataObject o = AtomHelper.getDataObject(oid);

		byte[] bertlv = o.getBytes();
		assertNotNull(bertlv);

		//Check blob length
		assertTrue(bertlv.length <= 20);
		
		assertTrue(bertlv[bertlv.length-1] == 0x00);
	}

**Comment by bob-fontana** [comment]
Fixed in e156c7ec21a51256b971efde16352a37f8b910a5.  Review ContainerLengthRule class.

**Comment by bob-fontana** [comment]
Really fixed in c6603ae178eb661ec3bb37a2e7b33f4e56aa681f
