### ISSUE TITLE
BER_TLVTests.java Length of value field tests not including the boundary values

### ISSUE THREAD

**Issue by MKSCertiPath** [GSA/piv-conformance#96]
The table in sp800-85B is as follows:

![image](https://user-images.githubusercontent.com/9324182/57024762-63686b00-6c03-11e9-9582-51d193dc2275.png)

The code in BER_TLVTests.java does not consider the two boundary values as inclusive of the value lengths for testing.

        if(lengthBytesCount == 1) {
        	//If length is 1 byte first between '00' and '7F'
        	
        	int l = firstByte.intValue();        	
        	assertTrue(l > 0);
        	assertTrue(l < 127);
        	
        	assertTrue(valueLength > 0);
        	assertTrue(valueLength < 127);
        	
        }else if(lengthBytesCount == 2) {
        	
        	//If length is 2 bytes first byte is '81'
        	assertTrue((firstByte & 0x81) == 0x81);
        	
        	assertTrue(valueLength > 0);
        	assertTrue(valueLength < 255);
        	
        }else if(lengthBytesCount == 3) {
        	
        	//If length is 3 bytes first byte is '82'
        	assertTrue((firstByte & 0x82)  == 0x82);
        	
        	assertTrue(valueLength > 0);
        	assertTrue(valueLength < 65535);
        	
        }else if(lengthBytesCount == 4) {
        	
        	//If length is 4 bytes first byte is '83'
        	assertTrue((firstByte & 0x83) == 0x83);
        	
        	assertTrue(valueLength > 0);
        	assertTrue(valueLength < 16777215);
        	
        }else if(lengthBytesCount == 5) {
        	
        	//If length is 5 bytes first byte is '84'
        	assertTrue((firstByte & 0x85) == 0x85);
        	
        	assertTrue(valueLength > 0);
        	
        	byte[] restLengthBytes = Arrays.copyOfRange(bertlv, aOffset + tagBytesCount + 1, lengthBytesCount);
        	
        	BigInteger lenValue = new BigInteger(restLengthBytes);
        	BigInteger f = new BigInteger("4294967295");
        	assertTrue(lenValue.compareTo(f) != 1);
        }

**Comment by bob-fontana** [comment]
Fixed and committed in 74350bd821ab725d119b36c8f401244ef3bc90ce
