### ISSUE TITLE
sp800_76Test_14: The comment and code don't match

### ISSUE THREAD

**Issue by MKSCertiPath** [GSA/piv-conformance#98]
//Confirm that the 20th and 21st is not null
		assertTrue(Byte.compare(biometricDataBlock[14], (byte)0x00) != 0, "Fingerprint capture equipment id is NULL");
		assertTrue(Byte.compare(biometricDataBlock[15], (byte)0x00) != 0, "Fingerprint capture equipment id is NULL");

The comment says to check 20th and 21st bytes whereas the code is checking 14th and 15th

**Comment by bob-fontana** [comment]
Fixed
